"use strict";

function parseAbi(raw) {
    const abi = typeof raw === "string" ? JSON.parse(raw) : raw;
    if (!Array.isArray(abi)) throw new Error("ABI must be a JSON array");
    return abi;
}

function mutatableFunctions(abi) {
    return abi.filter(
        (item) =>
            item.type === "function" &&
            item.stateMutability !== "view" &&
            item.stateMutability !== "pure"
    );
}

function formatParam(p) {
    const name = p.name || "param";
    return `${p.type} ${name}`;
}

function buildFuzzTest(fn) {
    const params = (fn.inputs || []).map(formatParam).join(", ");
    const callArgs = (fn.inputs || []).map((p) => p.name || "param").join(", ");
    const hasArgs = (fn.inputs || []).length > 0;

    const lines = [
        `    function testFuzz_${fn.name}(${params}) public {`,
    ];

    if (hasArgs) {
        (fn.inputs || []).forEach((p) => {
            if (p.type === "uint256" || p.type === "uint") {
                lines.push(`        ${p.name} = bound(${p.name}, 0, type(uint128).max);`);
            }
        });
    }

    lines.push(`        try target.${fn.name}(${callArgs}) {`);
    lines.push(`            // assert post-conditions here`);
    lines.push(`            // e.g. assertGe(target.totalSupply(), 0);`);
    lines.push(`        } catch {`);
    lines.push(`            // expected reverts are fine`);
    lines.push(`        }`);
    lines.push(`    }`);

    return lines.join("\n");
}

function buildInvariantTest(fn) {
    return [
        `    function invariant_${fn.name}_neverBreaksState() public {`,
        `        // assert protocol invariants after ${fn.name} calls`,
        `        // e.g. assertGe(target.totalSupply(), 0);`,
        `        //      assertLe(target.totalBorrowed(), target.totalDeposited());`,
        `    }`,
    ].join("\n");
}

function generate(contractName, abi) {
    const fns = mutatableFunctions(abi);

    const fuzzTests = fns.map(buildFuzzTest).join("\n\n");
    const invariantTests = fns.map(buildInvariantTest).join("\n\n");

    return `// SPDX-License-Identifier: MIT
// Auto-generated by avaguard-cli — review before production use
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";

interface I${contractName} {
${abi
    .filter((x) => x.type === "function")
    .map((fn) => {
        const inputs = (fn.inputs || []).map(formatParam).join(", ");
        const outputs = (fn.outputs || []).map((o) => o.type).join(", ");
        const retType = outputs ? ` returns (${outputs})` : "";
        return `    function ${fn.name}(${inputs}) external${retType};`;
    })
    .join("\n")}
}

contract ${contractName}FuzzTest is Test {
    I${contractName} target;

    function setUp() public {
        // target = I${contractName}(address(new ${contractName}(...)));
    }

${fuzzTests}
}

contract ${contractName}InvariantTest is Test {
    I${contractName} target;

    function setUp() public {
        // target = I${contractName}(address(new ${contractName}(...)));
        // targetContract(address(target));
    }

${invariantTests}
}
`;
}

module.exports = { generate, parseAbi, mutatableFunctions };
